[2025-07-31T21:56:07.266+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_tablea manual__2025-07-31T21:56:05.258875+00:00 [queued]>
[2025-07-31T21:56:07.276+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_tablea manual__2025-07-31T21:56:05.258875+00:00 [queued]>
[2025-07-31T21:56:07.277+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-31T21:56:07.298+0000] {taskinstance.py:1380} INFO - Executing <Task(PinotTableSubmitOperator): submit_tablea> on 2025-07-31 21:56:05.258875+00:00
[2025-07-31T21:56:07.310+0000] {standard_task_runner.py:57} INFO - Started process 2986 to run task
[2025-07-31T21:56:07.313+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_tablea', 'manual__2025-07-31T21:56:05.258875+00:00', '--job-id', '1174', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpzxluy9tn']
[2025-07-31T21:56:07.318+0000] {standard_task_runner.py:85} INFO - Job 1174: Subtask submit_tablea
[2025-07-31T21:56:07.380+0000] {task_command.py:415} INFO - Running <TaskInstance: table_dag.submit_tablea manual__2025-07-31T21:56:05.258875+00:00 [running]> on host d47ad9177d65
[2025-07-31T21:56:07.469+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_tablea' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T21:56:05.258875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T21:56:05.258875+00:00'
[2025-07-31T21:56:07.487+0000] {pinot_table_operator.py:28} ERROR - Pinot table failed to submit to Apache Pinot! 409 - {"code":409,"error":"Table config for account_dim_OFFLINE already exists. If this is unexpected, try deleting the table to remove all metadata associated with it."}
[2025-07-31T21:56:07.487+0000] {pinot_table_operator.py:32} ERROR - An error occured: Table submission failed with status code 409
[2025-07-31T21:56:07.497+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_tablea, execution_date=20250731T215605, start_date=20250731T215607, end_date=20250731T215607
[2025-07-31T21:56:07.537+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-31T21:56:07.553+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
