[2025-07-29T22:52:46.153+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_customer_dim manual__2025-07-29T22:52:45.699223+00:00 [queued]>
[2025-07-29T22:52:46.155+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_customer_dim manual__2025-07-29T22:52:45.699223+00:00 [queued]>
[2025-07-29T22:52:46.156+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-29T22:52:46.161+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_customer_dim> on 2025-07-29 22:52:45.699223+00:00
[2025-07-29T22:52:46.163+0000] {standard_task_runner.py:57} INFO - Started process 1442 to run task
[2025-07-29T22:52:46.165+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_customer_dim', 'manual__2025-07-29T22:52:45.699223+00:00', '--job-id', '908', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmpc64ucsa6']
[2025-07-29T22:52:46.168+0000] {standard_task_runner.py:85} INFO - Job 908: Subtask ingest_customer_dim
[2025-07-29T22:52:46.200+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_customer_dim manual__2025-07-29T22:52:45.699223+00:00 [running]> on host bec18a9c33c0
[2025-07-29T22:52:46.231+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='GGCODE' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_customer_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-29T22:52:45.699223+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-29T22:52:45.699223+00:00'
[2025-07-29T22:52:46.232+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-29T22:52:46.233+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/customer_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=customer_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimiter%22%3A%22%2C%22%7D"']
[2025-07-29T22:52:46.239+0000] {subprocess.py:86} INFO - Output:
[2025-07-29T22:52:46.243+0000] {subprocess.py:93} INFO - curl: (26) Failed to open/read local data from file/application
[2025-07-29T22:52:46.243+0000] {subprocess.py:97} INFO - Command exited with return code 26
[2025-07-29T22:52:46.249+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 26.
[2025-07-29T22:52:46.251+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dimension_batch_ingestion, task_id=ingest_customer_dim, execution_date=20250729T225245, start_date=20250729T225246, end_date=20250729T225246
[2025-07-29T22:52:46.258+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 908 for task ingest_customer_dim (Bash command failed. The command returned a non-zero exit code 26.; 1442)
[2025-07-29T22:52:46.303+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-29T22:52:46.316+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
